"""HITL Tools using ADK's built-in confirmation mechanism."""

from google.adk.tools import ToolContext


async def generate_proposal(
    request: str,
    proposal_type: str,
    tool_context: ToolContext,
) -> dict:
    """
    Generate a proposal and request human confirmation before finalizing.
    Uses ADK's built-in request_confirmation for true HITL.
    
    Args:
        request: What the user wants
        proposal_type: Type of proposal (e.g., "trip_plan", "code", "document")
        tool_context: ADK tool context
    
    Returns:
        dict with the proposal status
    """
    # Store the request context
    tool_context.state["current_request"] = request
    tool_context.state["proposal_type"] = proposal_type
    
    # The actual proposal content will be generated by the agent
    # This tool just sets up the confirmation flow
    return {
        "status": "ready_for_proposal",
        "message": f"Ready to generate {proposal_type} for: {request}",
        "next_step": "Generate the proposal content, then the confirmation will be requested"
    }


async def submit_for_approval(
    proposal_content: str,
    tool_context: ToolContext,
) -> dict:
    """
    Submit proposal for human approval using ADK's built-in confirmation.
    
    Args:
        proposal_content: The content to be approved
        tool_context: ADK tool context
    
    Returns:
        dict with approval result
    """
    # Store proposal in state
    tool_context.state["pending_proposal"] = proposal_content
    
    # Use ADK's built-in confirmation mechanism
    confirmation = await tool_context.request_confirmation(
        hint=f"Please review the proposal:\n\n{proposal_content}\n\nRespond with 'approve' to accept or provide feedback to reject.",
        payload={"approved": False, "feedback": ""}
    )
    
    if confirmation and confirmation.payload.get("approved", False):
        tool_context.state["approved_content"] = proposal_content
        return {
            "status": "approved",
            "message": "Proposal approved by human.",
            "content": proposal_content
        }
    else:
        feedback = confirmation.payload.get("feedback", "No specific feedback") if confirmation else "Rejected"
        tool_context.state["rejection_feedback"] = feedback
        tool_context.state["original_content"] = proposal_content
        return {
            "status": "rejected",
            "message": "Proposal rejected by human.",
            "feedback": feedback,
            "original_content": proposal_content
        }


async def rectify_proposal(
    improved_content: str,
    changes_made: str,
    tool_context: ToolContext,
) -> dict:
    """
    Submit rectified proposal for re-approval.
    
    Args:
        improved_content: The improved content
        changes_made: Description of what was changed
        tool_context: ADK tool context
    
    Returns:
        dict with approval result
    """
    original_feedback = tool_context.state.get("rejection_feedback", "")
    
    # Use ADK's built-in confirmation for re-approval
    confirmation = await tool_context.request_confirmation(
        hint=f"Rectified proposal based on feedback: '{original_feedback}'\n\nChanges made: {changes_made}\n\n{improved_content}\n\nRespond with 'approve' to accept or provide feedback to reject again.",
        payload={"approved": False, "feedback": ""}
    )
    
    if confirmation and confirmation.payload.get("approved", False):
        tool_context.state["approved_content"] = improved_content
        return {
            "status": "approved",
            "message": "Rectified proposal approved.",
            "content": improved_content
        }
    else:
        feedback = confirmation.payload.get("feedback", "No specific feedback") if confirmation else "Rejected again"
        tool_context.state["rejection_feedback"] = feedback
        tool_context.state["original_content"] = improved_content
        return {
            "status": "rejected",
            "message": "Rectified proposal rejected.",
            "feedback": feedback
        }


async def finalize_approved(
    summary: str,
    tool_context: ToolContext,
) -> dict:
    """
    Finalize the approved content.
    
    Args:
        summary: Summary of what was approved
        tool_context: ADK tool context
    
    Returns:
        dict confirming completion
    """
    approved_content = tool_context.state.get("approved_content", "")
    
    # Track history
    history = tool_context.state.get("execution_history", [])
    history.append({
        "content": approved_content,
        "summary": summary,
        "status": "finalized"
    })
    tool_context.state["execution_history"] = history
    
    # Clear state
    tool_context.state["pending_proposal"] = None
    tool_context.state["approved_content"] = None
    
    return {
        "status": "finalized",
        "summary": summary,
        "message": f"Workflow complete: {summary}"
    }
